_core:
  default_config_hash: 8WC1TgSq9JYHHD9R_8_azlnr-BMkH64LF2Ao7Br3kx4
socialicon_count: '5'
slideshow_count: '5'
slideshow_animation: slide
slideshow_display: '1'
slideshow_slide_speed: '7000'
slideshow_animation_speed: '600'
aegan_color: default
