_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  config: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  search: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  tome: 0
  tome_base: 0
  tome_static: 0
  tome_sync: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  views: 10
  standard: 1000
theme:
  olivero: 0
  claro: 0
  seven: 0
  adminimal_theme: 0
  acquia_claro: 0
  stable: 0
  classy: 0
  aegan: 0
  ajans: 0
  bartik: 0
  alz: 0
  amino_theme: 0
  amptheme: 0
  aristotle: 0
  barebones: 0
  barebones_enhanced: 0
  basic: 0
  bem: 0
  boldy: 0
  bootbase: 0
  bootstrap5_admin: 0
  bootstrap5basetheme: 0
  bootstrap_barrio: 0
  bootstrap5: 0
  bootstrap_cloud: 0
  bootstrap_italia: 0
  bootstrap_sass: 0
  bootstrap_storybook: 0
  bootstrap: 0
  bromo: 0
  businessplus_lite: 0
  catalog_lite: 0
  ceremai: 0
  chahmirian: 0
  clean_blog: 0
  colonel: 0
  conference_lite: 0
  corporate_lite: 0
  corporation: 0
  creative_innovative: 0
  creative_responsive_theme: 0
  dark_awesome: 0
  dawn: 0
  drulma: 0
  drupal8_zymphonies_theme: 0
  druparcheky_theme: 0
  stable9: 0
  thex: 0
  edux: 0
  electra: 0
  excellence_simple: 0
  fepper: 0
  firma: 0
  food_blog: 0
  fortytwo: 0
  starterkit_theme: 0
  holy: 0
  idyllic: 0
  lark: 0
  lightship: 0
  lupus_stark: 0
  magazine_lite: 0
  material_stable9: 0
  material_base: 0
  mili: 0
  minimal_lite: 0
  mobidic: 0
  moksu: 0
  neato: 0
  newsplus_lite: 0
  os_base: 0
  panache: 0
  particles_orange: 0
  pets_zymphonies_theme: 0
  photographer: 0
  portfolio_theme_explore: 0
  professional_responsive_theme: 0
  qatar2022_zymphonies_theme: 0
  radix: 0
  raspberry: 0
  restaurant_lite: 0
  rigel: 0
  ruhi: 0
  sailor: 0
  school_zymphonies_theme: 0
  seaside_admin: 0
  seven_dark: 0
  seventeen: 0
  simpleblog: 0
  smash_lite: 0
  socialbase: 0
  socialblue: 0
  startupgrowth_lite: 0
  subseven: 0
  tailwindcss: 0
  tara: 0
  thunder_admin: 0
  topplus_lite: 0
  used_cars: 0
  uswds: 0
  uswds_base: 0
  vartheme_bs4: 0
  vartheme_claro: 0
  visually_impaired_theme: 0
  webtheme: 0
  wonder_zymphonies_theme: 0
  writer: 0
  wxt_bootstrap: 0
  xara: 0
  zinble: 0
  zuvi: 0
profile: standard
