_core:
  default_config_hash: UqhgstKf5A7RbjtdqHQVc7iLvvDiVR4L8Fi3bcZ_z_0
general:
  wrap_content_in_container: true
hero:
  color: primary
forms:
  input_size: ''
  label_size: ''
  input_rounded: false
table:
  bordered: false
  striped: false
  narrow: false
  hoverable: false
  fullwidth: false
