_core:
  default_config_hash: uuzkPrlI5kFe5bq0RoMtc_1v6alxkZ8GLP6mr0khti8
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  logo: true
  name: true
  node_user_picture: true
  slogan: true
facebook_url: 'https://www.facebook.com/zymphonies'
twitter_url: 'https://twitter.com/zymphonies'
google_plus_url: 'https://plus.google.com/+ZymphoniesTechnologies'
linkedin_url: 'http://www.linkedin.com/company/zymphonies'
pinterest_url: 'https://www.pinterest.com/zymphonies'
rss_url: rss.xml
copyright_text: 'Copyright 2020· All rights reserved'
show_social_icon: 1
show_credit_link: 1
